"""Regenerate COMPARISON.md from scores.csv / stats JSON, and verify the numbers.

The comparison table in the paper is generated by this script rather than typed
by hand, so it cannot drift from the cached results.

    python src/make_comparison.py             # regenerate COMPARISON.md
    python src/make_comparison.py --verify    # check numbers against the published run
    python src/make_comparison.py --verify --tol 1.0

Exit code 1 on verification failure, so it can be used in CI.
"""
import argparse
import csv
import json
import sys

from config import OUT, ROOT

# Conditions that make up the three-way comparison.
METHODS = [
    ("C0", "A", "No context", "(nothing)"),
    ("C2", "B", "Terminology enumeration", "chmod, permission, execute, owner, ..."),
    ("C3", "C", "Syllabus as narration", "इस tutorial में हम Linux के file permissions समझेंगे। ..."),
]

SETTINGS = [
    ("test", "Utterance-level segments", "150 utterances, 5.7 s mean"),
    ("testcat", "Lecture-length spans", "100 spans, 26.2 s mean"),
]

# Published values from the run recorded in RUNLOG.md (2026-08-14, turbo).
# Verification compares a fresh run against these.
EXPECTED = {
    ("test", "C0"): dict(wer=85.69, k_wer=65.53, u_wer=43.50, script=32.6),
    ("test", "C2"): dict(wer=136.22, k_wer=31.55, u_wer=53.18, script=60.9),
    ("test", "C3"): dict(wer=99.35, k_wer=33.50, u_wer=41.68, script=60.0),
    ("testcat", "C0"): dict(wer=43.46, k_wer=48.04, u_wer=34.64, script=48.0),
    ("testcat", "C2"): dict(wer=62.86, k_wer=23.00, u_wer=46.42, script=70.3),
    ("testcat", "C3"): dict(wer=37.23, k_wer=21.38, u_wer=32.42, script=71.6),
}

# The qualitative claims the paper makes. These must hold for any valid
# replication, even if absolute WER shifts slightly across hardware/versions.
CLAIMS = [
    ("test", lambda s: s["C2"]["wer"] > s["C0"]["wer"],
     "B (terminology list) is WORSE than A on overall WER"),
    ("test", lambda s: s["C2"]["k_wer"] < s["C0"]["k_wer"],
     "B improves technical-term error over A"),
    ("test", lambda s: s["C2"]["u_wer"] > s["C0"]["u_wer"],
     "B degrades non-term error over A (the trade-off)"),
    ("test", lambda s: s["C3"]["wer"] < s["C2"]["wer"],
     "C (narration) beats B on overall WER"),
    ("test", lambda s: s["C3"]["u_wer"] < s["C0"]["u_wer"],
     "C does NOT degrade non-term error (unlike B)"),
    ("testcat", lambda s: s["C3"]["wer"] < s["C0"]["wer"],
     "C beats A on overall WER at lecture-length spans"),
    ("testcat", lambda s: s["C2"]["wer"] > s["C0"]["wer"],
     "B is still worse than A at lecture-length spans"),
    ("testcat", lambda s: s["C3"]["k_wer"] < s["C0"]["k_wer"],
     "C improves technical-term error at lecture-length spans"),
    ("testcat", lambda s: s["C3"]["script"] > s["C0"]["script"],
     "C improves script fidelity over A"),
]


def load_scores(model="turbo"):
    path = OUT / "scores.csv"
    if not path.exists():
        sys.exit(f"{path} missing — run score.py first")
    out = {}
    with path.open(encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if r["model"] != model:
                continue
            pct = lambda k: (float(r[k]) * 100 if r[k] not in ("", "None") else None)  # noqa: E731
            out.setdefault(r["split"], {})[r["cond"]] = dict(
                n=int(r["n"]), wer=pct("wer"), wer_sa=pct("wer_sa"),
                k_wer=pct("k_wer"), u_wer=pct("u_wer"), cer=pct("cer"),
                script=pct("script_fidelity"),
            )
    return out


def load_stats(model, split):
    p = OUT / f"stats__{model}__{split}.json"
    return json.loads(p.read_text()) if p.exists() else {}


def fmt_delta(st, key):
    if key not in st:
        return "—"
    s = st[key]
    lo, hi = s["ci"]
    return f"{s['corpus_delta']*100:+.2f} [{lo*100:+.2f}, {hi*100:+.2f}]"


def rel(new, old):
    return (new - old) / old * 100 if old else 0.0


def build_markdown(scores, model="turbo"):
    L = ["# Three ways to supply syllabus context to the decoder", ""]
    L += [
        "Hindi–English code-switched lecture ASR, MUCS 2021 / OpenSLR SLR104 test set,",
        f"`whisper-large-v3-turbo` (`{model}`), zero-shot. Lecture-disjoint split.",
        "",
        "> Generated by `src/make_comparison.py` from `out/scores.csv`. Do not edit by hand.",
        "",
        "| # | Method | What the decoder receives as context |",
        "|---|---|---|",
    ]
    for _, letter, name, example in METHODS:
        L.append(f"| **{letter}** | {name} | `{example}` |")
    L += ["", "All three decode identical audio with identical settings. Only the context changes.", ""]

    for split, title, subtitle in SETTINGS:
        if split not in scores:
            continue
        s, st = scores[split], load_stats(model, split)
        n = s["C0"]["n"]
        L += ["---", "", f"## {title} ({subtitle}, N={n})", ""]
        L += [
            "| Method | WER ↓ | ΔWER vs A [95% CI] | Technical-term error ↓ | "
            "Everything-else error ↓ | English in Latin script ↑ |",
            "|---|---|---|---|---|---|",
        ]
        for cond, letter, name, _ in METHODS:
            if cond not in s:
                continue
            r = s[cond]
            d = "—" if cond == "C0" else fmt_delta(st, f"C0->{cond}")
            L.append(
                f"| **{letter}** {name} | {r['wer']:.2f} | {d} | "
                f"{r['k_wer']:.2f} | {r['u_wer']:.2f} | {r['script']:.1f}% |"
            )
        if "C2->C3" in st:
            L += ["", f"**B vs C directly:** {fmt_delta(st, 'C2->C3')} in favour of narration."]
        L += [
            "",
            f"Relative to A: **B** changes term error by {rel(s['C2']['k_wer'], s['C0']['k_wer']):+.1f}% "
            f"and non-term error by {rel(s['C2']['u_wer'], s['C0']['u_wer']):+.1f}%; "
            f"**C** changes them by {rel(s['C3']['k_wer'], s['C0']['k_wer']):+.1f}% "
            f"and {rel(s['C3']['u_wer'], s['C0']['u_wer']):+.1f}%.",
            "",
        ]

    L += [
        "---", "",
        "## Reading",
        "",
        "**Terminology enumeration (B) is a bad trade.** It works on the words it targets —",
        "term error falls by roughly half in both settings — but error on every *other* word",
        "rises, and ordinary words dominate a sentence, so overall WER goes up.",
        "",
        "**Narration (C) gets the same term gain without the penalty.** Non-term error",
        "*improves* instead of degrading. On lecture-length spans this becomes a clear",
        "overall win.",
        "",
        "**Why:** the decoder's context channel is trained to receive the transcript of",
        "preceding speech. A delimited term list is out of distribution and destabilises",
        "generation; fluent narration is what the channel expects.",
        "",
        "⚠️ **Caveat.** Both settings mainly fix the *script* problem (English terms written",
        "in Devanagari where the reference uses Latin). A syllabus from the **wrong course**",
        "reproduces most of the gain — see `RUNLOG.md`. This is a format effect, not evidence",
        "that syllabus content is being used semantically.",
        "",
        "**Metrics.** WER: word error rate, lower is better; >100% is possible when the model",
        "inserts extra words. Absolute values are high because the corpus's segment boundaries",
        "are rounded to whole seconds (adjacent words bleed into each clip) and the decoder's",
        "repetition-repair fallback is disabled on purpose so instability stays measurable.",
        "All conditions carry this equally. CIs are paired bootstrap over utterances,",
        "10,000 resamples, seed 1337.",
        "",
    ]
    return "\n".join(L)


def verify(scores, tol):
    ok = True
    print(f"=== numeric check (tolerance ±{tol:.2f} WER points) ===")
    for (split, cond), exp in sorted(EXPECTED.items()):
        if split not in scores or cond not in scores[split]:
            print(f"  MISSING  {split}/{cond} — decode it first")
            ok = False
            continue
        got = scores[split][cond]
        for field in ("wer", "k_wer", "u_wer", "script"):
            d = abs(got[field] - exp[field])
            if d > tol:
                print(f"  FAIL  {split}/{cond} {field}: got {got[field]:.2f}, "
                      f"expected {exp[field]:.2f} (Δ{d:.2f})")
                ok = False
    if ok:
        print("  all values within tolerance of the published run")

    print("\n=== qualitative claims (must hold for any valid replication) ===")
    for split, fn, desc in CLAIMS:
        if split not in scores:
            print(f"  SKIP  [{split}] {desc}")
            continue
        try:
            passed = fn(scores[split])
        except KeyError:
            print(f"  SKIP  [{split}] {desc} — condition not decoded")
            continue
        print(f"  {'PASS' if passed else 'FAIL'}  [{split}] {desc}")
        ok &= passed
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="turbo")
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--tol", type=float, default=1.0,
                    help="allowed WER-point deviation from the published run")
    a = ap.parse_args()

    scores = load_scores(a.model)
    if not scores:
        sys.exit(f"no rows for model={a.model} in scores.csv")

    if a.verify:
        ok = verify(scores, a.tol)
        print("\nRESULT:", "replication verified" if ok else "replication MISMATCH")
        sys.exit(0 if ok else 1)

    path = ROOT / "COMPARISON.md"
    path.write_text(build_markdown(scores, a.model), encoding="utf-8")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
